### ISSUE TITLE
页面跳转问题

### ISSUE THREAD

**Issue by chenwenxian** [coolhwm/leshare-shop-wepy#27]
![image](https://user-images.githubusercontent.com/5305181/37144187-3bdf0d5a-22f8-11e8-8d35-0c2066d48e6e.png)
![image](https://user-images.githubusercontent.com/5305181/37144205-493feb18-22f8-11e8-90d3-636a21fbd7b2.png)
为什么点击跳转是报错，提示中多加了“pages/home”

**Comment by coolhwm** [comment]
代码已更新

**Comment by chenwenxian** [comment]
👌
