### ISSUE TITLE
授权问题，如何在本地把项目跑起来

### ISSUE THREAD

**Issue by CoderAha** [coolhwm/leshare-shop-wepy#3]
很感谢作者开源此项目，目前学习wepy中，希望能将项目在本地跑起来，学习下。 目前授权会报错，
提示 “请求微信验证失败，请求的code不可用。 数据:{errcode=40029, errmsg=invalid code, hints: [ req_id: yBKbka0058th19 ]}”，这个应该是本地的code与服务端不匹配的问题吧？

**Comment by coolhwm** [comment]
已提供截图和部分mock数据  @CoderLQChou
